matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        OS: linux

    - os: osx
      env:
        OS: darwin

sudo: required
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config
      - zip
      - g++
      - zlib1g-dev
      - unzip

jdk:
  - oraclejdk8

before_install:
  - wget "https://github.com/bazelbuild/bazel/releases/download/0.3.0/bazel-0.3.0-installer-${OS}-x86_64.sh"
  - chmod +x "bazel-0.3.0-installer-${OS}-x86_64.sh"
  - sudo "./bazel-0.3.0-installer-${OS}-x86_64.sh"

script:
  - bazel build //...
  - bazel test //...
